// constants/products.ts
export type Product = {
  id: number;
  title: string;
  category: string;
  image: string;
  description: string;
  designer: string;
  supplier: string;
  tags: string[];
  date: string;
  thumbnail: string;
};

export const products: Product[] = [
  {
    id: 1,
    title: "Crystal OFF White",
    category: "BASIC SERIES",
    image: "/1-OFFWhite.png",
    description:
      "Warm textures, timeless lines, and a calming palette. This kitchen brings together natural walnut grain, matte sage green cabinets, and brass details—for a soft yet elevated everyday experience.",
    designer: "kr_design323 x selinainteriorstyling",
    supplier: "cabinet ronbowcorp\nstone msisurfaces",
    tags: [
      "#WarmMinimalism",
      "#KitchenDesign",
      "#BayAreaHomes",
      "#GreenKitchen",
      "#WalnutCabinetry",
      "#KitchenInspo",
      "#Ronbow",
      "#InteriorDesign",
    ],
    date: "01 APRIL 2025",
    thumbnail: "/OFFWhite-1.png",
  },
  {
    id: 2,
    title: "Crystal Bright White",
    category: "BASIC SERIES",
    image: "/2-CrystalWhite.png",
    description:
      "Warm textures, timeless lines, and a calming palette. This kitchen brings together natural walnut grain, matte sage green cabinets, and brass details—for a soft yet elevated everyday experience.",
    designer: "kr_design323 x selinainteriorstyling",
    supplier: "cabinet ronbowcorp\nstone msisurfaces",
    tags: [
      "#WarmMinimalism",
      "#KitchenDesign",
      "#BayAreaHomes",
      "#GreenKitchen",
      "#WalnutCabinetry",
      "#KitchenInspo",
      "#Ronbow",
      "#InteriorDesign",
    ],
    date: "01 APRIL 2025",
    thumbnail: "/2-CrystalBrightWhite.png",
  },
  {
    id: 3,
    title: "Crystal Blue",
    category: "BASIC SERIES",
    image: "/3-CrystalBlue.png",
    description:
      "Warm textures, timeless lines, and a calming palette. This kitchen brings together natural walnut grain, matte sage green cabinets, and brass details—for a soft yet elevated everyday experience.",
    designer: "kr_design323 x selinainteriorstyling",
    supplier: "cabinet ronbowcorp\nstone msisurfaces",
    tags: [
      "#WarmMinimalism",
      "#KitchenDesign",
      "#BayAreaHomes",
      "#GreenKitchen",
      "#WalnutCabinetry",
      "#KitchenInspo",
      "#Ronbow",
      "#InteriorDesign",
    ],
    date: "01 APRIL 2025",
    thumbnail: "/3--CrystalBlue.png",
  },
  {
    id: 4,
    title: "Crystal Red",
    category: "BASIC SERIES",
    image: "/4B-CrystalRed.png",
    description:
      "Warm textures, timeless lines, and a calming palette. This kitchen brings together natural walnut grain, matte sage green cabinets, and brass details—for a soft yet elevated everyday experience.",
    designer: "kr_design323 x selinainteriorstyling",
    supplier: "cabinet ronbowcorp\nstone msisurfaces",
    tags: [
      "#WarmMinimalism",
      "#KitchenDesign",
      "#BayAreaHomes",
      "#GreenKitchen",
      "#WalnutCabinetry",
      "#KitchenInspo",
      "#Ronbow",
      "#InteriorDesign",
    ],
    date: "01 APRIL 2025",
    thumbnail: "/4-CrystalRed.png",
  },
  {
    id: 5,
    title: "Crystal Grey",
    category: "BASIC SERIES",
    image: "/5CrystalGrey.png",
    description:
      "Warm textures, timeless lines, and a calming palette. This kitchen brings together natural walnut grain, matte sage green cabinets, and brass details—for a soft yet elevated everyday experience.",
    designer: "kr_design323 x selinainteriorstyling",
    supplier: "cabinet ronbowcorp\nstone msisurfaces",
    tags: [
      "#WarmMinimalism",
      "#KitchenDesign",
      "#BayAreaHomes",
      "#GreenKitchen",
      "#WalnutCabinetry",
      "#KitchenInspo",
      "#Ronbow",
      "#InteriorDesign",
    ],
    date: "01 APRIL 2025",
    thumbnail: "/5Crystal-Grey.png",
  },
  {
    id: 6,
    title: "Grainy Dark Grey",
    category: "BASIC SERIES",
    image: "/6GrainyDarkGrey.png",
    description:
      "Warm textures, timeless lines, and a calming palette. This kitchen brings together natural walnut grain, matte sage green cabinets, and brass details—for a soft yet elevated everyday experience.",
    designer: "kr_design323 x selinainteriorstyling",
    supplier: "cabinet ronbowcorp\nstone msisurfaces",
    tags: [
      "#WarmMinimalism",
      "#KitchenDesign",
      "#BayAreaHomes",
      "#GreenKitchen",
      "#WalnutCabinetry",
      "#KitchenInspo",
      "#Ronbow",
      "#InteriorDesign",
    ],
    date: "01 APRIL 2025",
    thumbnail: "/6-GrainyDarkGrey.png",
  },
  {
    id: 7,
    title: "Grainy White",
    category: "BASIC SERIES",
    image: "/7-Grainywhite.png",
    description:
      "Warm textures, timeless lines, and a calming palette. This kitchen brings together natural walnut grain, matte sage green cabinets, and brass details—for a soft yet elevated everyday experience.",
    designer: "kr_design323 x selinainteriorstyling",
    supplier: "cabinet ronbowcorp\nstone msisurfaces",
    tags: [
      "#WarmMinimalism",
      "#KitchenDesign",
      "#BayAreaHomes",
      "#GreenKitchen",
      "#WalnutCabinetry",
      "#KitchenInspo",
      "#Ronbow",
      "#InteriorDesign",
    ],
    date: "01 APRIL 2025",
    thumbnail: "/7Grainywhite.png",
  },
  {
    id: 8,
    title: "Grainy Brown",
    category: "BASIC SERIES",
    image: "/8-GrainyBrown.png",
    description:
      "Warm textures, timeless lines, and a calming palette. This kitchen brings together natural walnut grain, matte sage green cabinets, and brass details—for a soft yet elevated everyday experience.",
    designer: "kr_design323 x selinainteriorstyling",
    supplier: "cabinet ronbowcorp\nstone msisurfaces",
    tags: [
      "#WarmMinimalism",
      "#KitchenDesign",
      "#BayAreaHomes",
      "#GreenKitchen",
      "#WalnutCabinetry",
      "#KitchenInspo",
      "#Ronbow",
      "#InteriorDesign",
    ],
    date: "01 APRIL 2025",
    thumbnail: "/8GrainyBrown.png",
  },
  {
    id: 9,
    title: "Grainy Iron",
    category: "BASIC SERIES",
    image: "/9-GrainyIron.png",
    description:
      "Warm textures, timeless lines, and a calming palette. This kitchen brings together natural walnut grain, matte sage green cabinets, and brass details—for a soft yet elevated everyday experience.",
    designer: "kr_design323 x selinainteriorstyling",
    supplier: "cabinet ronbowcorp\nstone msisurfaces",
    tags: [
      "#WarmMinimalism",
      "#KitchenDesign",
      "#BayAreaHomes",
      "#GreenKitchen",
      "#WalnutCabinetry",
      "#KitchenInspo",
      "#Ronbow",
      "#InteriorDesign",
    ],
    date: "01 APRIL 2025",
    thumbnail: "/9GrainyIron.png",
  },
  {
    id: 10,
    title: "Grainy Black",
    category: "BASIC SERIES",
    image: "/10-GrainyBlack.png",
    description:
      "Warm textures, timeless lines, and a calming palette. This kitchen brings together natural walnut grain, matte sage green cabinets, and brass details—for a soft yet elevated everyday experience.",
    designer: "kr_design323 x selinainteriorstyling",
    supplier: "cabinet ronbowcorp\nstone msisurfaces",
    tags: [
      "#WarmMinimalism",
      "#KitchenDesign",
      "#BayAreaHomes",
      "#GreenKitchen",
      "#WalnutCabinetry",
      "#KitchenInspo",
      "#Ronbow",
      "#InteriorDesign",
    ],
    date: "01 APRIL 2025",
    thumbnail: "/10GrainyBlack.png",
  },
  {
    id: 11,
    title: "Alaska White",
    category: "CALACATTA SERIES",
    image: "/1-Alaskawhite.png",
    description:
      "Warm textures, timeless lines, and a calming palette. This kitchen brings together natural walnut grain, matte sage green cabinets, and brass details—for a soft yet elevated everyday experience.",
    designer: "kr_design323 x selinainteriorstyling",
    supplier: "cabinet ronbowcorp\nstone msisurfaces",
    tags: [
      "#WarmMinimalism",
      "#KitchenDesign",
      "#BayAreaHomes",
      "#GreenKitchen",
      "#WalnutCabinetry",
      "#KitchenInspo",
      "#Ronbow",
      "#InteriorDesign",
    ],
    date: "01 APRIL 2025",
    thumbnail: "/1AlaskaWhite.png",
  },
  {
    id: 12,
    title: "Calacatta Alexa",
    category: "CALACATTA SERIES",
    image: "/2-CalacattaAlexa.png",
    description:
      "Warm textures, timeless lines, and a calming palette. This kitchen brings together natural walnut grain, matte sage green cabinets, and brass details—for a soft yet elevated everyday experience.",
    designer: "kr_design323 x selinainteriorstyling",
    supplier: "cabinet ronbowcorp\nstone msisurfaces",
    tags: [
      "#WarmMinimalism",
      "#KitchenDesign",
      "#BayAreaHomes",
      "#GreenKitchen",
      "#WalnutCabinetry",
      "#KitchenInspo",
      "#Ronbow",
      "#InteriorDesign",
    ],
    date: "01 APRIL 2025",
    thumbnail: "/2CalacattaAlexa.png",
  },
  {
    id: 13,
    title: "Calacatta Classic",
    category: "CALACATTA SERIES",
    image: "/3-Calacattaclassic.png",
    description:
      "Warm textures, timeless lines, and a calming palette. This kitchen brings together natural walnut grain, matte sage green cabinets, and brass details—for a soft yet elevated everyday experience.",
    designer: "kr_design323 x selinainteriorstyling",
    supplier: "cabinet ronbowcorp\nstone msisurfaces",
    tags: [
      "#WarmMinimalism",
      "#KitchenDesign",
      "#BayAreaHomes",
      "#GreenKitchen",
      "#WalnutCabinetry",
      "#KitchenInspo",
      "#Ronbow",
      "#InteriorDesign",
    ],
    date: "01 APRIL 2025",
    thumbnail: "/3Calacattaclassic.png",
  },
  {
    id: 14,
    title: "Calacatta Dally",
    category: "CALACATTA SERIES",
    image: "/4-CalacattaDally.png",
    description:
      "Warm textures, timeless lines, and a calming palette. This kitchen brings together natural walnut grain, matte sage green cabinets, and brass details—for a soft yet elevated everyday experience.",
    designer: "kr_design323 x selinainteriorstyling",
    supplier: "cabinet ronbowcorp\nstone msisurfaces",
    tags: [
      "#WarmMinimalism",
      "#KitchenDesign",
      "#BayAreaHomes",
      "#GreenKitchen",
      "#WalnutCabinetry",
      "#KitchenInspo",
      "#Ronbow",
      "#InteriorDesign",
    ],
    date: "01 APRIL 2025",
    thumbnail: "/4CalacattaDally.png",
  },
  {
    id: 15,
    title: "Calacatta Gold",
    category: "CALACATTA SERIES",
    image: "/5-CalacattaGold.png",
    description:
      "Warm textures, timeless lines, and a calming palette. This kitchen brings together natural walnut grain, matte sage green cabinets, and brass details—for a soft yet elevated everyday experience.",
    designer: "kr_design323 x selinainteriorstyling",
    supplier: "cabinet ronbowcorp\nstone msisurfaces",
    tags: [
      "#WarmMinimalism",
      "#KitchenDesign",
      "#BayAreaHomes",
      "#GreenKitchen",
      "#WalnutCabinetry",
      "#KitchenInspo",
      "#Ronbow",
      "#InteriorDesign",
    ],
    date: "01 APRIL 2025",
    thumbnail: "/5CalacattaGold.png",
  },
  {
    id: 16,
    title: "Calacatta Scott",
    category: "CALACATTA SERIES",
    image: "/6-CalacattaScott.png",
    description:
      "Warm textures, timeless lines, and a calming palette. This kitchen brings together natural walnut grain, matte sage green cabinets, and brass details—for a soft yet elevated everyday experience.",
    designer: "kr_design323 x selinainteriorstyling",
    supplier: "cabinet ronbowcorp\nstone msisurfaces",
    tags: [
      "#WarmMinimalism",
      "#KitchenDesign",
      "#BayAreaHomes",
      "#GreenKitchen",
      "#WalnutCabinetry",
      "#KitchenInspo",
      "#Ronbow",
      "#InteriorDesign",
    ],
    date: "01 APRIL 2025",
    thumbnail: "/6CalacattaScott.png",
  },
  {
    id: 17,
    title: "Calacatta Spider",
    category: "CALACATTA SERIES",
    image: "/7-CalacattaSpider.png",
    description:
      "Warm textures, timeless lines, and a calming palette. This kitchen brings together natural walnut grain, matte sage green cabinets, and brass details—for a soft yet elevated everyday experience.",
    designer: "kr_design323 x selinainteriorstyling",
    supplier: "cabinet ronbowcorp\nstone msisurfaces",
    tags: [
      "#WarmMinimalism",
      "#KitchenDesign",
      "#BayAreaHomes",
      "#GreenKitchen",
      "#WalnutCabinetry",
      "#KitchenInspo",
      "#Ronbow",
      "#InteriorDesign",
    ],
    date: "01 APRIL 2025",
    thumbnail: "/7CalacattaSpider.png",
  },
  {
    id: 18,
    title: "Exotic White",
    category: "CALACATTA SERIES",
    image: "/8-Exoticwhite.png",
    description:
      "Warm textures, timeless lines, and a calming palette. This kitchen brings together natural walnut grain, matte sage green cabinets, and brass details—for a soft yet elevated everyday experience.",
    designer: "kr_design323 x selinainteriorstyling",
    supplier: "cabinet ronbowcorp\nstone msisurfaces",
    tags: [
      "#WarmMinimalism",
      "#KitchenDesign",
      "#BayAreaHomes",
      "#GreenKitchen",
      "#WalnutCabinetry",
      "#KitchenInspo",
      "#Ronbow",
      "#InteriorDesign",
    ],
    date: "01 APRIL 2025",
    thumbnail: "/8Exoticwhite.png",
  },
  {
    id: 19,
    title: "Imperial White",
    category: "CALACATTA SERIES",
    image: "/9-Imperialwhite.png",
    description:
      "Warm textures, timeless lines, and a calming palette. This kitchen brings together natural walnut grain, matte sage green cabinets, and brass details—for a soft yet elevated everyday experience.",
    designer: "kr_design323 x selinainteriorstyling",
    supplier: "cabinet ronbowcorp\nstone msisurfaces",
    tags: [
      "#WarmMinimalism",
      "#KitchenDesign",
      "#BayAreaHomes",
      "#GreenKitchen",
      "#WalnutCabinetry",
      "#KitchenInspo",
      "#Ronbow",
      "#InteriorDesign",
    ],
    date: "01 APRIL 2025",
    thumbnail: "/9Imperialwhite.png",
  },
  {
    id: 20,
    title: "Olympia White",
    category: "CALACATTA SERIES",
    image: "/10-Olympiawhite.png",
    description:
      "Warm textures, timeless lines, and a calming palette. This kitchen brings together natural walnut grain, matte sage green cabinets, and brass details—for a soft yet elevated everyday experience.",
    designer: "kr_design323 x selinainteriorstyling",
    supplier: "cabinet ronbowcorp\nstone msisurfaces",
    tags: [
      "#WarmMinimalism",
      "#KitchenDesign",
      "#BayAreaHomes",
      "#GreenKitchen",
      "#WalnutCabinetry",
      "#KitchenInspo",
      "#Ronbow",
      "#InteriorDesign",
    ],
    date: "01 APRIL 2025",
    thumbnail: "/10Olympiawhite.png",
  },
  {
    id: 21,
    title: "Carrara Beige",
    category: "CARRARA SERIES",
    image: "/1-CarraraBeige.png",
    description:
      "Warm textures, timeless lines, and a calming palette. This kitchen brings together natural walnut grain, matte sage green cabinets, and brass details—for a soft yet elevated everyday experience.",
    designer: "kr_design323 x selinainteriorstyling",
    supplier: "cabinet ronbowcorp\nstone msisurfaces",
    tags: [
      "#WarmMinimalism",
      "#KitchenDesign",
      "#BayAreaHomes",
      "#GreenKitchen",
      "#WalnutCabinetry",
      "#KitchenInspo",
      "#Ronbow",
      "#InteriorDesign",
    ],
    date: "01 APRIL 2025",
    thumbnail: "/1CarraraBeige.png",
  },
  {
    id: 22,
    title: "Carrara Grey",
    category: "CARRARA SERIES",
    image: "/2-Carraragrey.png",
    description:
      "Warm textures, timeless lines, and a calming palette. This kitchen brings together natural walnut grain, matte sage green cabinets, and brass details—for a soft yet elevated everyday experience.",
    designer: "kr_design323 x selinainteriorstyling",
    supplier: "cabinet ronbowcorp\nstone msisurfaces",
    tags: [
      "#WarmMinimalism",
      "#KitchenDesign",
      "#BayAreaHomes",
      "#GreenKitchen",
      "#WalnutCabinetry",
      "#KitchenInspo",
      "#Ronbow",
      "#InteriorDesign",
    ],
    date: "01 APRIL 2025",
    thumbnail: "/2Carraragrey.png",
  },
  {
    id: 23,
    title: "Carrara White",
    category: "CARRARA SERIES",
    image: "/3-CarraraWhite.png",
    description:
      "Warm textures, timeless lines, and a calming palette. This kitchen brings together natural walnut grain, matte sage green cabinets, and brass details—for a soft yet elevated everyday experience.",
    designer: "kr_design323 x selinainteriorstyling",
    supplier: "cabinet ronbowcorp\nstone msisurfaces",
    tags: [
      "#WarmMinimalism",
      "#KitchenDesign",
      "#BayAreaHomes",
      "#GreenKitchen",
      "#WalnutCabinetry",
      "#KitchenInspo",
      "#Ronbow",
      "#InteriorDesign",
    ],
    date: "01 APRIL 2025",
    thumbnail: "/3CarraraDark.png",
  },
  {
    id: 24,
    title: "Carrara Bianco",
    category: "CARRARA SERIES",
    image: "/4-CarraraBianco.png",
    description:
      "Warm textures, timeless lines, and a calming palette. This kitchen brings together natural walnut grain, matte sage green cabinets, and brass details—for a soft yet elevated everyday experience.",
    designer: "kr_design323 x selinainteriorstyling",
    supplier: "cabinet ronbowcorp\nstone msisurfaces",
    tags: [
      "#WarmMinimalism",
      "#KitchenDesign",
      "#BayAreaHomes",
      "#GreenKitchen",
      "#WalnutCabinetry",
      "#KitchenInspo",
      "#Ronbow",
      "#InteriorDesign",
    ],
    date: "01 APRIL 2025",
    thumbnail: "/4CarraraBianco.png",
  },
  {
    id: 25,
    title: "Carrara Gold",
    category: "CARRARA SERIES",
    image: "/5-CarraraGold.png",
    description:
      "Warm textures, timeless lines, and a calming palette. This kitchen brings together natural walnut grain, matte sage green cabinets, and brass details—for a soft yet elevated everyday experience.",
    designer: "kr_design323 x selinainteriorstyling",
    supplier: "cabinet ronbowcorp\nstone msisurfaces",
    tags: [
      "#WarmMinimalism",
      "#KitchenDesign",
      "#BayAreaHomes",
      "#GreenKitchen",
      "#WalnutCabinetry",
      "#KitchenInspo",
      "#Ronbow",
      "#InteriorDesign",
    ],
    date: "01 APRIL 2025",
    thumbnail: "/5CarraraGold.png",
  },
  {
    id: 26,
    title: "Avalanche",
    category: "MULTI EXOTIC SERIES",
    image: "/1-Avalanche.png",
    description:
      "Warm textures, timeless lines, and a calming palette. This kitchen brings together natural walnut grain, matte sage green cabinets, and brass details—for a soft yet elevated everyday experience.",
    designer: "kr_design323 x selinainteriorstyling",
    supplier: "cabinet ronbowcorp\nstone msisurfaces",
    tags: [
      "#WarmMinimalism",
      "#KitchenDesign",
      "#BayAreaHomes",
      "#GreenKitchen",
      "#WalnutCabinetry",
      "#KitchenInspo",
      "#Ronbow",
      "#InteriorDesign",
    ],
    date: "01 APRIL 2025",
    thumbnail: "/1Avalanche.png",
  },
  {
    id: 27,
    title: "Bellingham",
    category: "MULTI EXOTIC SERIES",
    image: "/2-Bellingham.png",
    description:
      "Warm textures, timeless lines, and a calming palette. This kitchen brings together natural walnut grain, matte sage green cabinets, and brass details—for a soft yet elevated everyday experience.",
    designer: "kr_design323 x selinainteriorstyling",
    supplier: "cabinet ronbowcorp\nstone msisurfaces",
    tags: [
      "#WarmMinimalism",
      "#KitchenDesign",
      "#BayAreaHomes",
      "#GreenKitchen",
      "#WalnutCabinetry",
      "#KitchenInspo",
      "#Ronbow",
      "#InteriorDesign",
    ],
    date: "01 APRIL 2025",
    thumbnail: "/2Bellingham.png",
  },
  {
    id: 28,
    title: "Black Spider",
    category: "MULTI EXOTIC SERIES",
    image: "/3-BlackSpider.png",
    description:
      "Warm textures, timeless lines, and a calming palette. This kitchen brings together natural walnut grain, matte sage green cabinets, and brass details—for a soft yet elevated everyday experience.",
    designer: "kr_design323 x selinainteriorstyling",
    supplier: "cabinet ronbowcorp\nstone msisurfaces",
    tags: [
      "#WarmMinimalism",
      "#KitchenDesign",
      "#BayAreaHomes",
      "#GreenKitchen",
      "#WalnutCabinetry",
      "#KitchenInspo",
      "#Ronbow",
      "#InteriorDesign",
    ],
    date: "01 APRIL 2025",
    thumbnail: "/3BlackSpider.png",
  },
  {
    id: 29,
    title: "Canterbury",
    category: "MULTI EXOTIC SERIES",
    image: "/4-Canterbury.png",
    description:
      "Warm textures, timeless lines, and a calming palette. This kitchen brings together natural walnut grain, matte sage green cabinets, and brass details—for a soft yet elevated everyday experience.",
    designer: "kr_design323 x selinainteriorstyling",
    supplier: "cabinet ronbowcorp\nstone msisurfaces",
    tags: [
      "#WarmMinimalism",
      "#KitchenDesign",
      "#BayAreaHomes",
      "#GreenKitchen",
      "#WalnutCabinetry",
      "#KitchenInspo",
      "#Ronbow",
      "#InteriorDesign",
    ],
    date: "01 APRIL 2025",
    thumbnail: "/4Canterbury.png",
  },
  {
    id: 30,
    title: "Grainy Black",
    category: "BASIC SERIES",
    image: "/5-JeliskaWhite.png",
    description:
      "Warm textures, timeless lines, and a calming palette. This kitchen brings together natural walnut grain, matte sage green cabinets, and brass details—for a soft yet elevated everyday experience.",
    designer: "kr_design323 x selinainteriorstyling",
    supplier: "cabinet ronbowcorp\nstone msisurfaces",
    tags: [
      "#WarmMinimalism",
      "#KitchenDesign",
      "#BayAreaHomes",
      "#GreenKitchen",
      "#WalnutCabinetry",
      "#KitchenInspo",
      "#Ronbow",
      "#InteriorDesign",
    ],
    date: "01 APRIL 2025",
    thumbnail: "5JeliskaWhite.png",
  },
  {
    id: 31,
    title: "Vanilla Black",
    category: "MULTI EXOTIC SERIES",
    image: "/6-VanilaBlack.png",
    description:
      "Warm textures, timeless lines, and a calming palette. This kitchen brings together natural walnut grain, matte sage green cabinets, and brass details—for a soft yet elevated everyday experience.",
    designer: "kr_design323 x selinainteriorstyling",
    supplier: "cabinet ronbowcorp\nstone msisurfaces",
    tags: [
      "#WarmMinimalism",
      "#KitchenDesign",
      "#BayAreaHomes",
      "#GreenKitchen",
      "#WalnutCabinetry",
      "#KitchenInspo",
      "#Ronbow",
      "#InteriorDesign",
    ],
    date: "01 APRIL 2025",
    thumbnail: "6VanilaBlack.png",
  },
  {
    id: 32,
    title: "Rain Forest",
    category: "MULTI EXOTIC SERIES",
    image: "/7-RainForest.png",
    description:
      "Warm textures, timeless lines, and a calming palette. This kitchen brings together natural walnut grain, matte sage green cabinets, and brass details—for a soft yet elevated everyday experience.",
    designer: "kr_design323 x selinainteriorstyling",
    supplier: "cabinet ronbowcorp\nstone msisurfaces",
    tags: [
      "#WarmMinimalism",
      "#KitchenDesign",
      "#BayAreaHomes",
      "#GreenKitchen",
      "#WalnutCabinetry",
      "#KitchenInspo",
      "#Ronbow",
      "#InteriorDesign",
    ],
    date: "01 APRIL 2025",
    thumbnail: "7RainForest.png",
  },
  {
    id: 33,
    title: "Grainy Black",
    category: "BASIC SERIES",
    image: "/8-Oxford.png",
    description:
      "Warm textures, timeless lines, and a calming palette. This kitchen brings together natural walnut grain, matte sage green cabinets, and brass details—for a soft yet elevated everyday experience.",
    designer: "kr_design323 x selinainteriorstyling",
    supplier: "cabinet ronbowcorp\nstone msisurfaces",
    tags: [
      "#WarmMinimalism",
      "#KitchenDesign",
      "#BayAreaHomes",
      "#GreenKitchen",
      "#WalnutCabinetry",
      "#KitchenInspo",
      "#Ronbow",
      "#InteriorDesign",
    ],
    date: "01 APRIL 2025",
    thumbnail: "8Oxford.png",
  },
];
